### ISSUE TITLE
Broken with sphinx 3.5 on windows

### ISSUE THREAD

**Issue by AntoineD** [Chilipp/autodocsumm#45] opened 2021-04-01 07:55 UTC
Hello,

It works fine with Sphinx 3.4, see attach error log file.

[sphinx-err-dd25pm9e.log](https://github.com/Chilipp/autodocsumm/files/6241941/sphinx-err-dd25pm9e.log)

**Comment by EpicWink** [comment] 2021-04-11 04:19
Duplicate of $44

**Comment by Chilipp** [comment] 2021-04-15 11:57
Thanks for reporting @AntoineD, this issue has been closed via #42

**Closed by Chilipp** 2021-04-15 11:57 UTC
